import {targetOf} from './targeting.js';
import {validatePackage,plan,digest} from './core.js';
import {formBridge} from './adapter.js';
const $=id=>document.getElementById(id);let data=null,receipts={},events=[],busy=false;
const extension=typeof chrome!=='undefined'&&!!chrome.storage;
const store=async()=>{const state={data,receipts,events};if(extension)await chrome.storage.local.set({state});else localStorage.setItem('tg-assistant-demo',JSON.stringify(state));};
function note(text){$('message').textContent=text;}
function log(action,result){events.push({time:new Date().toISOString(),action,result});events=events.slice(-200);$('log').textContent=JSON.stringify(events,null,2);}
function draw(){ $('rows').replaceChildren();$('summary').replaceChildren();$('empty').hidden=!!data;
 if(!data)return;
 for(const [label,value] of [['Объявления',data.ads.length],['Бюджет пакета',`${data.ads.reduce((s,a)=>s+a.budget,0).toFixed(2)} TON`],['Общий предел',`${data.totalBudget} TON`]]){const d=document.createElement('div');d.className='card';d.textContent=label;const b=document.createElement('strong');b.textContent=value;d.append(b);$('summary').append(d);}
 for(const row of plan(data,receipts)){const a=data.ads.find(x=>x.id===row.id);const tr=document.createElement('tr');for(const text of [a.title,targetOf(a).type,a.cpm.toFixed(2),a.budget.toFixed(2),row.externalId?`Существующее №${row.externalId}`:row.action==='verify_before_repeat'?'Форма заполнена, не сохранено':'Готово к подготовке']){const td=document.createElement('td');td.textContent=text;tr.append(td);}const td=document.createElement('td'),btn=document.createElement('button');btn.textContent='Заполнить форму';btn.disabled=!!a.externalId||busy||row.action==='verify_before_repeat';btn.onclick=()=>prepare(a);td.append(btn);tr.append(td);$('rows').append(tr);}
}
async function target(){if(!extension)throw Error('Это локальный предпросмотр. Для доступа к форме установите расширение и нажмите его значок во вкладке Telegram Ads.');const {targetTab}=await chrome.storage.session.get('targetTab');if(!targetTab)throw Error('Нажмите значок расширения в нужной вкладке Telegram Ads.');return targetTab;}
async function invoke(command,ad){const tabId=await target();const result=await chrome.scripting.executeScript({target:{tabId},func:formBridge,args:[command,ad??null]});if(!result[0]?.result)throw Error('Нет подтверждения от формы');return result[0].result;}
async function prepare(ad){if(busy)return;busy=true;draw();try{const currentErrors=validatePackage(data);if(currentErrors.length)throw Error(currentErrors.join('\n'));const result=await invoke('prepare',ad);receipts[ad.id]={...result,at:new Date().toISOString(),packageHash:await digest(data)};log('prepare', {id:ad.id,...result});note('Поля заполнены. Каналы, медиа и статус требуют проверки. Ничего не опубликовано.');await store();}catch(e){log('error',String(e.message));note(e.message);}finally{busy=false;draw();}}
async function load(p){const errors=validatePackage(p);if(errors.length)throw Error(errors.join('\n'));if(data&&JSON.stringify(data)!==JSON.stringify(p)&&!confirm('Заменить текущий локальный пакет? Журнал останется, отметки заполнения будут сброшены.'))return;const unchanged=data&&JSON.stringify(data)===JSON.stringify(p);data=p;if(!unchanged)receipts={};log('import',{id:p.id,hash:await digest(p),ads:p.ads.length});await store();draw();note('Пакет проверен и готов к работе.');}
$('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024)throw Error('JSON больше 2 MB');await load(JSON.parse(await file.text()));}catch(err){note(err.message);}e.target.value='';};
$('example').onclick=async()=>{try{await load(await (await fetch('fixtures/example.json')).json());}catch(e){note(e.message);}};
$('inspect').onclick=async()=>{try{const result=await invoke('inspect');log('inspect',result);await store();note('Структура открытой формы записана в журнал.');}catch(e){note(e.message);}};
$('export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({version:1,package:data,receipts,events},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='telegram-ads-receipts.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
$('clear').onclick=async()=>{if(!confirm('Удалить локальный пакет и журнал? Объявления в Telegram не изменятся.'))return;data=null;receipts={};events=[];await store();$('log').textContent='Нет действий';draw();note('Локальные данные удалены.');};
try{const saved=extension?(await chrome.storage.local.get('state')).state:JSON.parse(localStorage.getItem('tg-assistant-demo')||'null');if(saved){if(saved.data&&validatePackage(saved.data).length===0)data=saved.data;receipts=saved.receipts||{};events=saved.events||[];$('log').textContent=JSON.stringify(events,null,2);}draw();}catch(e){note('Не удалось восстановить локальные данные: '+e.message);}
